In [ ]:
import numpy as np
from scipy import stats as st


In [ ]:
matrix_a = np.random.randint(1, 11, size=(3, 3))
matrix_b = np.random.randint(1, 11, size=(3, 3))

print(matrix_a)
print(matrix_b)

[[5 2 8]
 [1 2 5]
 [5 7 5]]
[[1 1 6]
 [7 6 1]
 [4 5 8]]


In [ ]:
matrix_c = matrix_a + matrix_b
print(matrix_c)

[[ 6  3 14]
 [ 8  8  6]
 [ 9 12 13]]


In [ ]:
matrix_d = matrix_a.dot(matrix_b)

In [ ]:
matrix_d

array([[51, 57, 96],
       [35, 38, 48],
       [74, 72, 77]])

In [ ]:
a_mean = np.mean(matrix_a)
b_mean = np.mean(matrix_b)
d_mean = np.mean(matrix_d)

In [ ]:
print(a_mean)
print(b_mean)
print(d_mean)

4.444444444444445
4.333333333333333
60.888888888888886


In [ ]:
a_mode = st.mode(matrix_a)
b_mode = st.mode(matrix_b)
d_mode = st.mode(matrix_d)

In [ ]:
print(a_mode)
print(b_mode)
print(d_mode)

ModeResult(mode=array([5, 2, 5]), count=array([2, 2, 2]))
ModeResult(mode=array([1, 1, 1]), count=array([1, 1, 1]))
ModeResult(mode=array([35, 38, 48]), count=array([1, 1, 1]))


In [ ]:
a_std = np.std(matrix_a)
b_std = np.std(matrix_b)
d_std = np.std(matrix_d)

In [ ]:
print(a_std)
print(b_std)
print(d_std)

2.2166597048066667
2.581988897471611
19.03473108962459


In [ ]:
a_var = (a_std)**2
b_var = (b_std)**2
d_var = (d_std)**2

In [ ]:
print(a_var)
print(b_var)
print(d_var)

4.913580246913579
6.666666666666666
362.3209876543209


In [ ]:
a_t = np.transpose(matrix_a)

In [ ]:
print(a_t)

[[5 1 5]
 [2 2 7]
 [8 5 5]]


In [ ]:
deter1 = np.linalg.det(matrix_a)

In [ ]:
print(deter1)

-108.99999999999997


In [ ]:
deter2 = np.linalg.det(matrix_b)

In [ ]:
print(deter2)

57.00000000000001


In [ ]:
if deter1 != 0:
    a_inv = np.linalg.inv(matrix_a)


In [ ]:
print(a_inv)

[[ 0.2293578  -0.42201835  0.05504587]
 [-0.18348624  0.13761468  0.1559633 ]
 [ 0.02752294  0.2293578  -0.0733945 ]]


In [ ]:
if deter2 != 0:
    b_inv = np.linalg.inv(matrix_b)

In [ ]:
print(b_inv)

[[ 0.75438596  0.38596491 -0.61403509]
 [-0.9122807  -0.28070175  0.71929825]
 [ 0.19298246 -0.01754386 -0.01754386]]
