In [1]:
import numpy as np

In [2]:
array = np.arange(0, 11)

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array[4]

4

In [5]:
array[-2]

9

In [6]:
array[0:4]

array([0, 1, 2, 3])

In [10]:
var = np.array([[1, 2, 3], 
                [5, 10, 15], 
                [20, 30, 40]])

In [11]:
var

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [20, 30, 40]])

In [15]:
var[0][1]

2

In [16]:
var[0, 1]

2

In [17]:
var[2, 2]

40

In [18]:
var[-1, 0]

20

In [19]:
array[0:3]

array([0, 1, 2])

In [20]:
array[3::2]

array([3, 5, 7, 9])

In [21]:
var[0:3]

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [20, 30, 40]])

In [22]:
var

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [20, 30, 40]])

In [23]:
var[0:2, 1:3]

array([[ 2,  3],
       [10, 15]])

In [25]:
array1 = np.array([[2, 3, 4, 5, 6],
                 [6, 7, 8, 4, 2],
                 [10, 11, 12, 14, 15]])

In [26]:
array1

array([[ 2,  3,  4,  5,  6],
       [ 6,  7,  8,  4,  2],
       [10, 11, 12, 14, 15]])

In [28]:
array1[::2, ::2]

array([[ 2,  4,  6],
       [10, 12, 15]])

In [29]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
array[0] = 11

In [31]:
array

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
array[0:3] = 11

In [33]:
array

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
array[0:2] = 10, 11

In [35]:
array

array([10, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
example = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

In [3]:
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
example[1, 1] = 100

In [5]:
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [6]:
example[2, 2] = 100

In [7]:
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80, 100]])

In [8]:
example[:, 2] = 100

In [9]:
example

array([[ 10,  20, 100],
       [ 40, 100, 100],
       [ 70,  80, 100]])

In [11]:
example[0::2]

array([[ 10,  20, 100],
       [ 70,  80, 100]])

In [12]:
example[ : , 0:2]

array([[ 10,  20],
       [ 40, 100],
       [ 70,  80]])

In [13]:
example[0::2, 0:2]

array([[10, 20],
       [70, 80]])

In [14]:
example[0::2, 0:2] = 100

In [15]:
example

array([[100, 100, 100],
       [ 40, 100, 100],
       [100, 100, 100]])

In [19]:
example[0]

array([100, 100, 100])

In [21]:
example[0] = 10, 20, 30

In [22]:
example

array([[ 10,  20,  30],
       [ 40, 100, 100],
       [100, 100, 100]])

In [25]:
example[0][0:1]

array([10])

In [26]:
example[0, 0:1]

array([10])

In [28]:
fancy = np.arange(0, 50, 5)

In [29]:
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [30]:
[fancy[1], fancy[3], fancy[5]]

[5, 15, 25]

In [31]:
indexes = [1, 3, 5]

In [32]:
fancy[indexes]

array([ 5, 15, 25])

In [33]:
array = np.array([1, 3, 5])

In [34]:
array

array([1, 3, 5])

In [35]:
fancy[array]

array([ 5, 15, 25])

In [36]:
variable = np.zeros((10, 10), dtype='int')

In [37]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
variable.shape

(10, 10)

In [39]:
variable.shape[0]

10

In [40]:
row = variable.shape[0]

In [41]:
for i in range(row):
    variable[i] = i

In [42]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [43]:
list1 = [1, 3, 5, 7]

In [44]:
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [45]:
list2 = [8, 5, 2, 7, 3]

In [46]:
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [2]:
example = np.arange(1, 17).reshape((4, 4))

In [3]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
example[[0, 3],[1, 2]]

array([ 2, 15])

In [5]:
row = [0, 2, 3, 1]
col = [0, 2, 2, 3]

In [6]:
example[row, col]

array([ 1, 11, 15,  8])

In [7]:
val = np.arange(0, 16).reshape((4, 4))

In [8]:
val

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
val[1, [1, 3]]

array([5, 7])

In [11]:
val[[0, 3], 1]

array([ 1, 13])

In [12]:
val[0:, [1, 2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [18]:
val[1:3, [1, 2]]

array([[ 5,  6],
       [ 9, 10]])